# Generated by Django 5.1.7 on 2025-06-29 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetTurnosIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_turno', models.DateField()),
                ('disponible', models.BooleanField()),
                ('estado_vehiculo', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('mantenimiento', 'Mantenimiento')], max_length=20)),
                ('vehiculo_operativo', models.BooleanField()),
                ('turno_asignado', models.BooleanField()),
                ('transportista', models.ForeignKey(limit_choices_to={'rol': 'TRANSP'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
